# Generated by Django 2.0 on 2017-12-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_interaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
