# Generated by Django 2.0 on 2017-12-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171221_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startingWeight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
