# Generated by Django 2.0 on 2017-12-21 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20171221_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ownerPk',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, related_name='ownerPk', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
