# Generated by Django 2.0 on 2017-12-07 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdeemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('calories', models.FloatField(verbose_name='Calories')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ('user', 'date'),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.FloatField(null=True, verbose_name='Goal weight'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='starting_weight',
            field=models.FloatField(null=True, verbose_name='Starting weight'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weekly_weight_change',
            field=models.FloatField(null=True, verbose_name='Goal weight loss per week'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tdeemanager.Profile', verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('user', 'date')},
        ),
    ]
